# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
