# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_auto_20181004_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
